### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by yannisc** [bhamodi/facebook-online-friend-tracker#1]
Thanks for your script!

I try to run it on Mac and I get:

Waiting for Facebook to update friends list... (This takes approximately 2 minutes.)
Traceback (most recent call last):
  File "/usr/local/bin/facebook-online-friend-tracker", line 9, in <module>
    load_entry_point('facebook-online-friend-tracker==1.2.0', 'console_scripts', 'facebook-online-friend-tracker')()
  File "/Library/Python/2.7/site-packages/src/main.py", line 72, in main
    onlineFriendsCount = int(driver.find_element_by_xpath('//*[@id="fbDockChatBuddylistNub"]/a/span[2]/span').text.strip('()'))
ValueError: invalid literal for int() with base 10: ''

**Comment by bhamodi** [comment]
Hi @yannisc,
Thanks for submitting an issue!
So, the ValueError that we are seeing here means that we tried to apply the `int()` function on an empty string. This means that when we tried to scrape the value of `fbDockChatBuddylistNub` for the number of online friends, it couldn't find a number.

So some possible scenarios:
1) Is it possible that when you ran the script, there were no online friends?
2) When the tool opens the Chrome window, do you see this?
<img width="226" alt="screen shot 2015-07-13 at 9 37 31 am" src="https://cloud.githubusercontent.com/assets/7663987/8655023/3dcc55ca-2943-11e5-952a-fcad1a40e394.png">

**Comment by yannisc** [comment]
I tried from another mac with smaller screen size and it worked!

I see that when the screen is wider, this "Chat (44)" is not shown. When the window is resized to less width, it appears. So, maybe a smaller window size is the solution.

**Comment by bhamodi** [comment]
Awesome! Thanks for the detailed report @yannisc. :+1: 
I just sent out a fix for this issue in this commit: https://github.com/bhamodi/facebook-online-friend-tracker/commit/bce2f1b3fe4c8877616b5e37aff1493fd232787d. The script now explicitly sets the window size of the Chromedriver. This fix can be found in `v1.2.1` of the script.

To upgrade your script, you must run: `pip install facebook-online-friend-tracker --upgrade`
Please let me know if this resolves the issue so that we can close this issue!

**Comment by yannisc** [comment]
Yes, that solved that! Thanks a lot!

**Comment by bhamodi** [comment]
No problem! :+1:
